### PR TITLE
Update example output

### PR DESCRIPTION
**Pull request by Rawk**
Update example output after changes in https://github.com/elastic/ecs-logging-python/pull/28.

### CODE REVIEW

**Review by basepi — COMMENTED** [review]
Thanks for this! Please sign [the CLA](https://www.elastic.co/contributor-agreement) when you get a chance.

**Review by basepi — APPROVED** [review]

**Comment by basepi** [comment]
@Rawk did you get a chance to sign the CLA? Not sure if the tool hasn't updated or if you haven't had a chance to sign it.

**Comment by Rawk** [comment]
I did sign the agreement, almost immediately. Maybe there is something more i have to do after signing it?

I signed it again today, in case something went wrong the last time.

**Comment by sethmlarson** [comment]
Looks like the CLA status is correct now, sometimes takes some time to apply to PRs :)

**Review by sethmlarson — APPROVED** [review]

**Pull request merged**
