### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by MrSnapperVibes**
Repeat of #100 because CI in order to fix CI issues.

* Remove unused imports
* Undefined name index

### CODE REVIEW

**Comment by MrSnapperVibes** [comment]
Hmm, it looks like we're stuck in CI again.

This particular pull request is not a big deal. This library is useful and I'd love to be helpful, but there doesn't appear that there's much that needs done 🙂

**Comment by basepi** [comment]
Yeah but I also need to figure out why the CI isn't running 🤔

Appreciate your patience.

@elastic/observablt-ci any ideas why these tests aren't running? They don't even show up under the "Checks" tab where I could restart them.

**Review by basepi — APPROVED** [review]

**Comment by v1v** [comment]
> @elastic/observablt-ci any ideas why these tests aren't running? 

For some reason, this project has been configured with:

image

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks


I'll change the settings now

**Comment by v1v** [comment]
according to [this](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork)

> If you are comfortable with running workflows on the pull request branch, return to the  Conversation tab, and under "Workflow(s) awaiting approval", click Approve and run.


But I cannot see anything, in theory, something like the below screenshot should be shown

image

**Comment by v1v** [comment]
And I've just seen this

image

**Pull request merged**
