### PR TITLE
Update readme ecs version

### PR DESCRIPTION
**Pull request by NZTimKeegan**
Replaces references to version 1.5 with 1.6 as latest release implements
ecs version 1.6

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
Thanks, could you sign the CLA?

**Comment by NZTimKeegan** [comment]
Sure thing - I've followed the link and filled in the form

**Comment by sethmlarson** [comment]
Let's do a quick close-open-cycle! :recycle:

**Comment by sethmlarson** [comment]
@NZTimKeegan Btw did you sign the CLA with the same email address as the one you have as the "author" on the commit?

**Comment by NZTimKeegan** [comment]
> @NZTimKeegan Btw did you sign the CLA with the same email address as the one you have as the "author" on the commit?

I think I may have used a different address - I'll sign it again now

**Review by sethmlarson — APPROVED** [review]
Woo, thanks for this!

**Comment by sethmlarson** [comment]
@NZTimKeegan btw do you require a hacktoberfest-accepted label?

**Comment by NZTimKeegan** [comment]
> @NZTimKeegan btw do you require a hacktoberfest-accepted label?

No thanks @sethmlarson, just happy to make a small contribution. 

This library is great btw, I came across it yesterday morning and got it working in our latest release in 10 minutes. Thanks 😊

**Pull request merged**
