### PR TITLE
support lists

### LINKED ISSUE #21: does not support a dictionary of list of strings
Currently `normalize_dict` blows up on the following if added the the tests

```python
assert normalize_dict({"a": ["1", "2"]}) == {"a": ["1", "2"]}
```

Given the type signature it seems like this should be supported. It looks like since `normalize_dict` is deconstructing any lists with
```python
        elif isinstance(val, list):
            val[:] = [normalize_dict(x) for x in val]
```
this assumption is that all elements in the list are also dictionaries. It seems like it should be okay to have a list of non dictionary items.

### PR DESCRIPTION
**Pull request by camerondavison**
Closes #21

### CODE REVIEW

**Comment by camerondavison** [comment]
I signed the CLA

**Comment by sethmlarson** [comment]
Jenkins test this please

**Comment by sethmlarson** [comment]
jenkins test this please

**Comment by sethmlarson** [comment]
Looks like linting failed, could you run `nox -s blacken` to fix some of the issues?

```
09:08:14  nox > Running session lint
09:08:14  nox > Creating virtual environment (virtualenv) using python in .nox/lint
09:08:15  nox > pip install flake8 black mypy
09:08:25  nox > black --check --target-version=py27 noxfile.py tests/ ecs_logging/
09:08:25  would reformat /var/lib/jenkins/workspace/hon_ecs-logging-python-mbp_PR-22/src/go.elastic.co/apm/ecs-logging-python/tests/test_utils.py
09:08:25  Oh no! 💥 💔 💥
09:08:25  1 file would be reformatted, 12 files would be left unchanged.
09:08:25  nox > Command black --check --target-version=py27 noxfile.py tests/ ecs_logging/ failed with exit code 1
09:08:25  nox > Session lint failed.
```

**Comment by sethmlarson** [comment]
Thanks for this change! :tada:

**Comment by camerondavison** [comment]
Sure thing. When do y'all do releases so I can get the change deployed into my env?

**Comment by sethmlarson** [comment]
I can create a release for this today probably.

**Pull request merged**
